# permissions for end users to edit skydiveanalyzers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skydiveanalyzer-editor-role
rules:
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveanalyzers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveanalyzers/status
  verbs:
  - get
