# permissions for end users to view skydiveagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skydiveagents-viewer-role
rules:
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveagents/status
  verbs:
  - get
